### ISSUE TITLE
Fix CI/CD Versioning in 

### ISSUE THREAD

**Issue by Guibod** [Guibod/scrap-trawler#17]
Description:
Currently, Cocogitto does not update package.json when bumping versions. This can lead to inconsistencies between the Git tag and the package.json version.

Steps to Fix:
Add a post-bump hook in cog.toml to update package.json after every bump.
Ensure the updated version is committed.

Example Fix (cog.toml):
```toml
[hooks]
post-bump = "pnpm sync-version && git add package.json && git commit -m 'chore: sync package.json version'"

```

Example Fix (sync-version.ts):
```typescript
import { writeFileSync } from "fs";
import { execSync } from "child_process";

const version = execSync("git describe --tags --abbrev=0").toString().trim();
const packageJson = JSON.parse(readFileSync("./package.json", "utf8"));

packageJson.version = version;
writeFileSync("./package.json", JSON.stringify(packageJson, null, 2) + "\n");

console.log(`Updated package.json to version ${version}`);

```
